### ISSUE TITLE
Dialogs disappear on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [scoute-dich/PDFCreator#10]
When I perform this sequence of events, the dialog on screen disappears:

Sequence 1:
1. Click on Text To PDF
2. Enter Text
3. Click on Done button
4. Orientation Change

Sequence 2-3:
1. Click on +image
2. Click on:
a. Take photo
b. Choose File
3. Orientation Change

Sequence 4:
 1. Click on +image
2. Select a photo
3. Click on Edit Image
4. Click on Pick Filter
5. Orientation Change

Sequence 5-10:
1. Click on +Text
2. Enter Text
3. Click on:
a. Delete
b. Merge
c. Encrypt
d. Edit Metadata
d. Edit Metadata + Create new metadata
e. Choose File
4. Orientation Change

Sequence 11-13
1. Click on ...
2. Click on Settings
3. Click on:
a. Image quality
b. Custom Directory
c. License
4. Orientation Change

Sequence 14:
1. Click on ...
2. Click on Help
3. Orientation Change

**Comment by scoute-dich** [comment]
Then open it again it's only one click... (Or don't rotate tour device).
