### ISSUE TITLE
Scrollable view changes state on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [scoute-dich/PDFCreator#11]
When I perform this sequence of events, the scroll view on screen goes back to the top:

1. Click on ...(More Options)
2. Scroll Down
3. Orientation Change

**Comment by scoute-dich** [comment]
Then don't scroll... (Or don't rotate tour device).

**Comment by reverse-unina** [comment]
Why should I? I can simply uninstall it

**Comment by scoute-dich** [comment]
Yes, that's also a possibility.
