### ISSUE TITLE
Edit pdf

### ISSUE THREAD

**Issue by sunil-singh-chaudhary** [scoute-dich/PDFCreator#13]
hello Can you  pls tell how to edit pre pdf file like edit moon to soon on a pdf file You are just adding image or text on pdf file  pls help

**Comment by scoute-dich** [comment]
On the most right tab "text|..." You can edit existing pdf files. Please read the help dialog. Some pdf files are protected against manipulating. In this case the app can't help you.

**Comment by sunil-singh-chaudhary** [comment]
sorry but its not like that i have open pdf then select where to edit and save like that any  solution or update on that

**Comment by scoute-dich** [comment]
Sorry, but I don't understand your problem. This app is only for basic manipulations "on the fly". Of you want to do more advanced operations you should consider to install an app with more advanced features or edit the pdf on the PC with a program specially designed for manipulating pdf files.
