### ISSUE TITLE
App force closing on Marshmallow 6.0.1 while opening 

### ISSUE THREAD

**Issue by sachoosaini** [scoute-dich/PDFCreator#16]
The app is force closing and unable to open when first time started. This is because the application does not ask for using storage permission in marshmallow. But when I manually allowed application from permissions menu to allow using storage. Then app started itself. I am attaching logact for the same. [http://pastebin.com/q8CNzphh](url)

**Comment by scoute-dich** [comment]
Hi,

thanks for reporting. This bug was caused by the new file manager. I fixed it.

**Comment by sachoosaini** [comment]
@scoute-dich great..
