### ISSUE TITLE
Force Close app when scrolling between tabs video attached. 

### ISSUE THREAD

**Issue by sachoosaini** [scoute-dich/PDFCreator#17]
Marshmallow 6.0.1 ROM exodus

[http://pastebin.com/La2Lhw9r](url) 
The app force close when you scroll between tabs. Attaching logcat for the same along with the

**Comment by scoute-dich** [comment]
Also my mistake. Fixed.

**Comment by sachoosaini** [comment]
@scoute-dich so when this going to rectified ? next build ??

**Comment by scoute-dich** [comment]
I just released version 2.9. So an update should be available in the next days on F-Droid.

**Comment by sachoosaini** [comment]
ohk.cool.

**Comment by scoute-dich** [comment]
;-)
