### ISSUE TITLE
Random order in image chooser 

### ISSUE THREAD

**Issue by Tonat** [scoute-dich/PDFCreator#18]
I don't find the build in image chooser particular helpful at the moment. It seems to display the images in some random (?) order, so having hundreds of photos, I can't find the ones I want to import... 
     Could they either be **sorted by date** (latest ones first) or could you provide the **option to choose** them **from the gallery**?
Thanks, the app is really handy nevertheless!!!

PDFCreator 3.0, Android 7.0 (TouchWiz)

**Comment by scoute-dich** [comment]
This will be improved in next release. It's already fixed. Thanks to:
[https://github.com/Mariovc/ImagePicker](https://github.com/Mariovc/ImagePicker)
