### ISSUE TITLE
Spanish language translation

### ISSUE THREAD

**Issue by sebastian05067** [scoute-dich/PDFCreator#19]
Hello, 

I wanted to tell you two things

1) I would like to translate your application into Spanish, are you interested?. If so,
can you create a folder for spanish language?

2) I see that your application has a lot of potential, but I think it would have more potential if you joined with Open Note Scanner, you would be very competitive together in the Google Play Store. Have you thought about that idea?

Regards

**Comment by scoute-dich** [comment]
Hi,

thanks for wanting to translate. I added the folder with two files, containing the original English strings. About your second question... I haven't thought about it till now.

Regards
Gaukler Faun
