### ISSUE TITLE
Disable notification on file operations

### ISSUE THREAD

**Issue by licaon-kter** [scoute-dich/PDFCreator#24]
...like delete, it's useless.

I have the device in hand, I pressed delete, what's the point?

**Comment by scoute-dich** [comment]
Do you mean the confirmation prompt when deleting a file? If yes this is, this is intended to prevent users from deleting a file accidentally. It happens to me several times...

**Comment by licaon-kter** [comment]
Nope, after the confirmation I get an actual notification.
