### ISSUE TITLE
Quality issues for image conversion

### ISSUE THREAD

**Issue by licaon-kter** [scoute-dich/PDFCreator#25]
Sony/Samsung 6.0.1
Versions: 3.5, 3.6 and 3.7

While having image quality at 100% or 80% or 60% (it does not matter!!!), using two 1**Mb** JPEGs:
* in app, add first image, default Album/Gallery app, create, +IMAGE add second image, create -> result 179**kb** PDF file (quality was, as expected at that size, really bad)
* via TotalCommander, first image send to app, create -> result 1**Mb** PDF file (fine quality)
* then continue in app +IMAGE, create -> result 1.1**Mb** PDF file (first page as above, fine; second page as first case, really bad)

**Comment by scoute-dich** [comment]
I can confirm that and will look into it. Thanks for reporting.

**Comment by scoute-dich** [comment]
This is fixed. Will release a update soon. Thanks again.
