### ISSUE TITLE
Crash if refused Storage permission

### ISSUE THREAD

**Issue by licaon-kter** [scoute-dich/PDFCreator#26]
Sony 6.0.1
Version 3.7
logcat: https://gist.github.com/licaon-kter/f0682c0359e4fe229071bf6721414c27

**Comment by scoute-dich** [comment]
It seems to be a problem when picking a file. Can you reproduce the steps to get the force close?

**Comment by licaon-kter** [comment]
Looks like if you refuse Storage access this happens, I guess the app should handle this and not think it has this permission by default.

eg. if you have an overlay type app Android will not grant Storage permission when your app asks for it, but it asks you to disable said app first (if you have several you need to disable them all until it lets you do that), so you might not do that right away and go back to your app, hence crash

**Comment by scoute-dich** [comment]
I've fixed it. Now of the permissions are not granted a prompt will appear to grant the permission.
