### ISSUE TITLE
Menu icon issue

### ISSUE THREAD

**Issue by licaon-kter** [scoute-dich/PDFCreator#27]
Pic: https://lut.im/q20lPGuLOI/16Uf2K36g4bT7xO4.jpeg

Sony 5.1.1 with changed DPI to 424 via ADB.

IIRC, this looked ok on Sony 6.0.1

**Comment by scoute-dich** [comment]
Does this look normal with default dpi?

**Comment by licaon-kter** [comment]
Yes, restoring it to default (480) will fix it.
Must be a bug in some lib.

**Comment by scoute-dich** [comment]
Ok. Then nothing to do for me.
