### ISSUE TITLE
PDF from Web Pages?

### ISSUE THREAD

**Issue by AlphaOmega3** [scoute-dich/PDFCreator#5]
I hope I do not ask idiotic, but it would be possible to add the ability to create PDF files directly from Web pages? for example, a plug-in to open the page in the app and save it

**Comment by scoute-dich** [comment]
That's possible. My weather app can save a whole webpage as screenshot. so I have the code already. I must think a about it. At the moment I don't have much time. So it, when I decide to implement it, you must wait... But good idea. Thanks for the comment.

**Comment by AlphaOmega3** [comment]
Hey! thanks to the availability. Rather (regardless of when), I would like to ask you to add this skill to these browsers:
Lightning, Orfox, I2P .. if possible

**Comment by scoute-dich** [comment]
I thought a little about it, and decided, that I won't implement this. It would need a whole new activity (webview), and new permissions (internet access).

You can make a screenshot and share it to my app.

I also don't plan to implement a pdf export function in other browsers. Please open an issue in the depending projects.

**Comment by AlfaOmega33** [comment]
Wait, there is an app, "save for offline".. you may add an integration with this app for resolve the problem..
