### ISSUE TITLE
Missing file manager

### ISSUE THREAD

**Issue by Primokorn** [scoute-dich/PDFCreator#6]
Hi,

I didn't change the app directory but PDF Creator doesn't detect my file managers (Menu > Open app folder). I have FX file manager and MiXplorer.

Thank you.

**Comment by scoute-dich** [comment]
I have the same issue with amaze file manager. In fact that's not the fault of my app. The developers of the concerning file managers should implement an intent-filter to open files/directories. Same file managers have this implemented (e.g. Cyanogenmod default file manager, 3c toolbox). So i think, if you do not want to use an other file manager you must contact the support of FX file manager and MiXplorer.

**Comment by Primokorn** [comment]
I'll do, thanks.
